// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTask.Infrastructure.Persistence;

#nullable disable

namespace TestTask.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6637533b-5b83-459e-9af0-ad845623c82a"),
                            Name = "HDD 1TB",
                            Price = 74.090000000000003,
                            Quantity = 55
                        },
                        new
                        {
                            Id = new Guid("c50b7f72-cecb-4d50-a14b-cf354d8d00ea"),
                            Name = "HDD SSD 512GB",
                            Price = 190.99000000000001,
                            Quantity = 102
                        },
                        new
                        {
                            Id = new Guid("50634dda-79b7-49ec-9152-249b5a265096"),
                            Name = "RAM DDR4 16GB",
                            Price = 80.319999999999993,
                            Quantity = 47
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5378659e-9248-48dc-93f9-942748a14da3"),
                            PasswordHash = "U+CMicHhIuvh3W73vtQ1LE9SIr0WweXjdnfHam8if+g=",
                            Role = "Admin",
                            UserName = "Test1"
                        },
                        new
                        {
                            Id = new Guid("d1b89e0b-548d-45bd-9309-ac9ddd30f740"),
                            PasswordHash = "U+CMicHhIuvh3W73vtQ1LE9SIr0WweXjdnfHam8if+g=",
                            Role = "User",
                            UserName = "Test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
